import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { inter400 } from "./fonts/fonts";
import { AuthProvider } from "./context/authContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter400.className} ${inter400.className} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
